version: '3.7'
services:
  webapp:
    build: .
    image: weather-demoapp:latest
    ports:
      - 5001:5001
    depends_on:
      - nginx-service
  nginx-service:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./static:/usr/share/nginx/static
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
 
