#
# See this Helm chart for options
# https://github.com/benc-uk/helm-charts/tree/master/webapp
#

image:
  repository: bencuk/dotnet-demoapp
  tag: latest
  pullPolicy: Always

service:
  targetPort: 5000
  type: LoadBalancer