name: Build Windows Image

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]

# Note. Required secrets: dockerPassword, acrPassword

env:
  dockerUser: bencuk
  acrName: bcdemo
  imageName: dotnet-demoapp
  # Use Windows container Nanoserver base image
  imageBase: 3.1-nanoserver-1809

jobs:
  buildJob:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'
      
    - name: Build the Docker image
      run: docker build . --build-arg IMAGE_BASE=$imageBase --tag $dockerUser/$imageName:nanoserver --tag $acrName.azurecr.io/apps/$imageName:nanoserver
      shell: bash
    
    - name: Dockerhub Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ env.dockerUser }}
        password: ${{ secrets.dockerPassword }} 

    - name: Push to Dockerhub
      run: docker push $dockerUser/$imageName
      shell: bash
      
    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.acrName }}.azurecr.io
        username: ${{ env.acrName }}
        password: ${{ secrets.acrPassword }}   
            
    - name: Push to ACR
      run: docker push $acrName.azurecr.io/apps/$imageName
      shell: bash
